name: flyinsky
publish_to: 'none'
version: 2.1.0
environment:
  sdk: ^3.7.2
dependencies:
  google_fonts: ^6.2.1
  http: ^1.4.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_pdfview: ^1.4.0+1
  flutter_dotenv: ^6.0.0
  sqflite: ^2.4.2
  rive: ^0.13.20
  google_mobile_ads: ^6.0.0
  new_version_plus: ^0.1.1
  supabase_flutter: ^2.10.3
  in_app_purchase: ^3.2.3
  bcrypt: ^1.1.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/splash_fly.riv
   - .env